import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vcrFont = localFont({
  src: [
    {
      path: "../public/fonts/VCROSDMono.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/VCROSDMono.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-vcr",
  display: "swap",
});

const trajanFont = localFont({
  src: [
    {
      path: "../public/fonts/TrajanPro-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/TrajanPro-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-trajan",
  display: "swap",
});

const fullAutomationFont = localFont({
  src: [
    {
      path: "../public/fonts/FullAutomation.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/FullAutomation.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-full-automation",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfolio of Tarder TCZ",
  description: "Generated by Tarder TCZ",
};

import { ThemeProvider } from "@/components/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vcrFont.variable} ${trajanFont.variable} ${fullAutomationFont.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
